title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# [Name of visual theme]
#theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0

# [Conversion]
markdown: kramdown

# [Used rubygem plugins]
plugins:
  - jekyll-remote-theme
  - jemoji
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - CONTRIBUTING.md
  - LICENSE.md
  - CODE_OF_CONDUCT.md
