name: Test Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v2
      with:
        ruby-version: 3.2.2

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Run tests with coverage
      run: bundle exec rspec

    #- name: Upload coverage to Codecov
    #  uses: codecov/codecov-action@v2
    #  with:
    #    token: ${{ secrets.CODECOV_TOKEN }}
    #    fail_ci_if_error: true
